### ISSUE TITLE
Add support for gometalinter

### ISSUE THREAD

**Issue by derekperkins** [reviewdog/errorformat#20]
https://github.com/alecthomas/gometalinter already normalizes the output for most Go static check tools, so the hard work is mostly done. I would also hope that the output (`[govet]` below) would show the subtool used rather than always `[gometalinter]`, but that's a minor point.

![image](https://user-images.githubusercontent.com/3588778/32515053-109b0568-c3bc-11e7-9102-7c2cd8d7c8ea.png)

**Comment by derekperkins** [comment]
cc @alecthomas

**Comment by alecthomas** [comment]
gometalinter supports formatting output via text/template... It seems like it might be simpler to just format output for vim directly

**Comment by derekperkins** [comment]
@alecthomas I've been implementing https://github.com/haya14busa/reviewdog on our projects today and it's pretty great. Normally if a build fails, you have to dig through the Travis logs to see what happened, but this takes the output and creates a legit GitHub review on the actual lines that are throwing the errors. I've got it running on `go vet` and `golint` already, and I'd love to be able to pipe in any of the `gometalinter` tools.

**Comment by haya14busa** [comment]
btw, gometalinter seems to support checkstyle xml format https://github.com/alecthomas/gometalinter#checkstyle-xml-format .

So actually we don't need to implement errorformat for gometalinter to use reviewdog. reviewdog supports checkstyle xml format too.

but it might be useful for other cases to add errorformat, so I can include #21.

Thanks
