### ISSUE TITLE
Escape ANSI-codes

### ISSUE THREAD

**Issue by vk26** [reviewdog/errorformat#51]
Hi. Many CLI tools output highlighted, colorized text. Special ANSI-codes are used in this cases. For example ruby linter fasterer output:
```
fasterer | cat -A
^[[0;31;49mtestdata/examples.rb:3^[[0m Array#shuffle.first is slower than Array#sample.$
```
where `^[[0;31;49m ... ^[[0m` - red-color ANSI-codes.
I tried to handle this ANSI-codes via efm masks, but i didn't cope with it. May be is there solution for escaping ANSI-codes?

**Comment by mgrachev** [comment]
@vk26 👋You can use something in the middle to remove ANSi-codes. For example:
```
fasterer  | sed 's/\x1b\[[0-9;]*m//g' | cat -A
```

**Comment by vk26** [comment]
@mgrachev Good idea! Thanks :+1:
